// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
CANJaguar* bADherderdeployright;
CANJaguar* bADherderdeployleft;
CANJaguar* conveyorMotor;
CANJaguar* intakeMotor;
CANJaguar* shooter1Motor;
CANJaguar* shooter2Motor;
CANJaguar* frontLeftMotor;
CANJaguar* rearLeftMotor;
CANJaguar* frontRightMotor;
CANJaguar* rearRightMotor;
	
DigitalInput* frontLightSensor;
DigitalInput* middleLightSensor;
DigitalInput* backLightSensor;
Encoder* shooterEncoder;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	bADherderdeployright = new CANJaguar(2);	
	bADherderdeployleft = new CANJaguar(3);
	conveyorMotor = new CANJaguar(4);
	intakeMotor = new CANJaguar(5);
	shooter1Motor = new CANJaguar(6);
	shooter2Motor = new CANJaguar(7);
	frontLeftMotor = new CANJaguar(8);
	rearLeftMotor = new CANJaguar(9);
	frontRightMotor = new CANJaguar(10);
	rearRightMotor = new CANJaguar(1);
	
	frontLightSensor = new DigitalInput(7);
	middleLightSensor = new DigitalInput(8);
	backLightSensor = new DigitalInput(9);
	shooterEncoder = new Encoder(1, 2);
	

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
