// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "IN.h"
#include "../Robotmap.h"
#include "../Robot.h"
#include "../Commands/off.h"
IN::IN() : Subsystem("IN") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	nTKCJ = RobotMap::intakeMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
  void IN::Set(double val){
	  
	 nTKCJ->Set(val);
	 
  }
	float IN::Get()
	{
		return nTKCJ->Get();
	}
void IN::InitDefaultCommand() {
	
	
	// Set the default command for a subsystem here.
	SetDefaultCommand(new off());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}
// Put methods for controlling this subsystem
// here. Call these from Commands.
